### ISSUE TITLE
Building city vs building settlement

### ISSUE THREAD

**Issue by kevinjreece** [cjs-smith1993/Settlers#3]
The Board doesn't have any logic for returning a Settlement to a Player when it is upgraded to a city.

**Comment by connorsmith256** [comment]
That's right. In fact, the board currently won't allow a city to be placed because a dwelling will already exist at that location, so placeDwelling is really like placeSettlement right now. I'm thinking of separating the logic into placeSettlement and placeCity, since it seems like the two are pretty distinct. placeCity would then make sure there's a settlement there and if there is, it would replace the settlement with the given city and return the settlement that was there, so the facade could give it back to the player.
